# Generated by Django 4.2.6 on 2023-12-13 11:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("products", "0003_alter_product_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "pk_id",
                    models.BigAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.blocks.CharBlock(
                                    form_classname="title", label="Заголовок"
                                ),
                            ),
                            ("paragraph", wagtail.blocks.RichTextBlock(label="Текст")),
                            (
                                "image",
                                wagtail.images.blocks.ImageChooserBlock(
                                    label="Изображение"
                                ),
                            ),
                            (
                                "gallery",
                                wagtail.blocks.ListBlock(
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Фото"
                                    ),
                                    label="Галерея фото",
                                ),
                            ),
                        ],
                        use_json_field=True,
                        verbose_name="Контент",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата новости")),
                (
                    "pic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="news",
                        to="products.product",
                        verbose_name="Товары",
                    ),
                ),
            ],
            options={
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
