# Generated by Django 4.2.6 on 2024-01-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="pk_id",
        ),
        migrations.RemoveField(
            model_name="post",
            name="products",
        ),
        migrations.AlterField(
            model_name="post",
            name="page_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="wagtailcore.page",
            ),
        ),
    ]
