# Generated by Django 4.2.6 on 2024-01-02 10:57

import datetime
from django.db import migrations, models
import imagekit.models.fields
import promo.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                (
                    "title2",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Заголовок 2",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True, max_length=250, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "button_link",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Ссылка на кнопке",
                    ),
                ),
                (
                    "button_title",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Текст на кнопке",
                    ),
                ),
                (
                    "pic",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to=promo.models.Promo.get_pic_path,
                        verbose_name="фото",
                    ),
                ),
                (
                    "start",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Старт акции"
                    ),
                ),
                (
                    "end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Завершение акции"
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
            },
        ),
    ]
