# Generated by Django 4.2.6 on 2024-01-03 11:27

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields
import imagekit.models.fields
import promo.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_image_alter_product_rim_type_and_more"),
        ("promo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("slug", models.SlugField(max_length=150)),
                (
                    "pic",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to=promo.models.Portfolio.get_pic_path,
                        verbose_name="фото",
                    ),
                ),
                ("content", froala_editor.fields.FroalaField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Портфолио",
                "verbose_name_plural": "Портфолио",
            },
        ),
        migrations.CreateModel(
            name="PortfolioProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="порядок")),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="promo.portfolio",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="products.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары в Портфолио",
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="PortfolioImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pic",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to=promo.models.PortfolioImage.get_pic_path,
                        verbose_name="фото",
                    ),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="порядок")),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promo.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото",
                "verbose_name_plural": "Фото",
                "ordering": ("sort",),
            },
        ),
    ]
