# Generated by Django 4.2.6 on 2023-12-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="current_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=12,
                null=True,
                verbose_name="Текущая Стоимость",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=12,
                null=True,
                verbose_name="Скидка",
            ),
        ),
    ]
