# Generated by Django 4.2.6 on 2023-12-20 07:56

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import src.other.enums


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unload_service",
            field=django_enum_choices.fields.EnumChoiceField(
                blank=True,
                choice_builder=django_enum_choices.choice_builders.value_value,
                choices=[("FORTOCHKI", "FORTOCHKI"), ("STARCO", "STARCO")],
                enum_class=src.other.enums.UnloadServiceType,
                max_length=9,
                null=True,
            ),
        ),
    ]
