# Generated by Django 4.2.6 on 2023-12-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_current_price_alter_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                default=0,
                max_digits=12,
                verbose_name="Скидка",
            ),
        ),
    ]
