# Generated by Django 4.2.6 on 2023-12-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_order_products_order_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="accept_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время подтверждения"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="accepted",
            field=models.BooleanField(default=False, verbose_name="Подтвержден"),
        ),
    ]
