# Generated by Django 4.2.6 on 2023-12-12 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "verbose_name": "Брэнд товара",
                "verbose_name_plural": "Брэнды Товаров",
            },
        ),
    ]
