# Generated by Django 4.2.6 on 2023-12-17 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalCard",
            fields=[
                (
                    "pk_id",
                    models.BigAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Наименование полное"
                    ),
                ),
                (
                    "legal_address",
                    models.CharField(
                        blank=True, max_length=215, verbose_name="Юридический адрес"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=215, verbose_name="Почтовый адрес"
                    ),
                ),
                ("inn", models.IntegerField(blank=True, null=True, verbose_name="ИНН")),
                ("kpp", models.IntegerField(blank=True, null=True, verbose_name="КПП")),
                ("bik", models.IntegerField(blank=True, null=True, verbose_name="БИК")),
                (
                    "ogrn",
                    models.IntegerField(blank=True, null=True, verbose_name="ОГРН"),
                ),
                (
                    "settlement",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Расчетный счет"
                    ),
                ),
                (
                    "korr",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Корр счет"
                    ),
                ),
                (
                    "general_director",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Генеральный директор"
                    ),
                ),
            ],
            options={
                "verbose_name": "ЮР Карточка",
                "verbose_name_plural": "ЮР Карточки",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "pk_id",
                    models.BigAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="Почта"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=250, verbose_name="ФИО"),
                ),
                (
                    "is_legal",
                    models.BooleanField(default=False, verbose_name="Юридическое лицо"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles",
                        to="locations.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профиль",
            },
        ),
    ]
