# Generated by Django 4.2.6 on 2023-12-12 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("unloads", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Unload",
            new_name="UnloadScheduler",
        ),
    ]
