# Generated by Django 4.2.6 on 2023-12-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unloads", "0002_rename_unload_unloadscheduler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unloadscheduler",
            name="rim_unload",
            field=models.BooleanField(default=True, verbose_name="Выгрузка дисков"),
        ),
        migrations.AlterField(
            model_name="unloadscheduler",
            name="tire_unload",
            field=models.BooleanField(default=True, verbose_name="Выгрузка шин"),
        ),
    ]
