# Generated by Django 4.2.6 on 2023-12-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "pk_id",
                    models.BigAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("code", models.CharField(max_length=50, verbose_name="КОД")),
                (
                    "percent_discount",
                    models.IntegerField(verbose_name="Скидка в процентах"),
                ),
                (
                    "amount_discount",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=8,
                        verbose_name="Фиксированная сумма скидки",
                    ),
                ),
                (
                    "all_products",
                    models.BooleanField(
                        default=False,
                        help_text="Действует на все продукты",
                        verbose_name="Все продукты",
                    ),
                ),
                ("expire_time", models.DateTimeField(verbose_name="Дата завершения")),
                ("is_active", models.BooleanField(verbose_name="Активно")),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="promocodes",
                        to="products.product",
                        verbose_name="Товары",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
            },
        ),
    ]
